---

- hosts: all
  become: true
  tasks:

  - name: update repositories and install apache with php  
    package: 
      name:
        - "{{ apache_pack }}"
        - "{{ php_pack }}"
      state: latest
      update_cache: yes
