---

- hosts: all
  become: true
  tasks:

  - name: update repositories and install apache with php on ubuntu
    package: 
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: update repositories and install apache with php on centos
    dnf:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"
