---

- hosts: all
  become: true
  tasks:

  - name: updates index and installs apache2 and php packages on ubuntu
    apt: 
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: updates index and installs httpd and php packages on centos
    dnf:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes 
    when: ansible_distribution == "CentOS"
