---

- hosts: all
  become: true
  tasks:

  - name: removes apache2 package on ubuntu
    apt: 
      name: apache2
      state: absent
    when: ansible_distribution == "Ubuntu"

  - name: removes php support for apache on ubuntu
    apt:
      name: libapache2-mod-php
      state: absent
    when: ansible_distribution == "Ubuntu"

  - name: removes httpd package on centos
    dnf:
      name: httpd
      state: absent
    when: ansible_distribution == "CentOS"

  - name: removes php on centos
    dnf:
      name: php
      state: absent
    when: ansible_distribution == "CentOS"  
